default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "fastlane/AuthKey/api_key.p8",
      in_house: false
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "App/App.xcodeproj",
      team_id: "5NBF6H2RRL"
    )

    build_app(
      project: "App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath \"#{Dir.pwd}/fastlane/AuthKey/api_key.p8\" -authenticationKeyID \"#{ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']}\" -authenticationKeyIssuerID \"#{ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']}\""
    )

    upload_to_testflight
  end

  desc "Push a new release build to the App Store"
  lane :release do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: "fastlane/AuthKey/api_key.p8",
      in_house: false
    )

    update_code_signing_settings(
      use_automatic_signing: true,
      path: "App/App.xcodeproj",
      team_id: "5NBF6H2RRL"
    )

    build_app(
      project: "App/App.xcodeproj",
      scheme: "App",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates -authenticationKeyPath \"#{Dir.pwd}/fastlane/AuthKey/api_key.p8\" -authenticationKeyID \"#{ENV['APP_STORE_CONNECT_API_KEY_KEY_ID']}\" -authenticationKeyIssuerID \"#{ENV['APP_STORE_CONNECT_API_KEY_ISSUER_ID']}\""
    )

    upload_to_app_store(
      submit_for_review: true,
      automatic_release: true
    )
  end
end
