with open('src/App.jsx', 'rb') as f:
    src = f.read().decode('utf-8')

print(f"Loaded {len(src)} chars")

# ── 1. INSERT MODALS before closing fragment ──────────────────────────────────
FRAGMENT_CLOSE = "      )}\r\n    </>\r\n  );\r\n}\r\n"

modals = (
    "\r\n"
    "      {/* ═══ ROTATE NOW OVERLAY ══════════════════════════════ */}\r\n"
    "      {showRotateNow && (\r\n"
    "        <div onClick={() => setShowRotateNow(false)} style={{\r\n"
    "          position:'fixed',inset:0,zIndex:9999,display:'flex',flexDirection:'column',\r\n"
    "          alignItems:'center',justifyContent:'center',\r\n"
    "          background:'rgba(5,7,20,0.97)',backdropFilter:'blur(20px)',cursor:'pointer',\r\n"
    "        }}>\r\n"
    "          <div style={{fontSize:'5rem',marginBottom:'16px',animation:'pulse 1s infinite'}}>&#128260;</div>\r\n"
    "          <h1 style={{fontSize:'2.8rem',fontWeight:'900',color:'#fff',letterSpacing:'-0.03em',margin:'0 0 8px'}}>ROTATE NOW</h1>\r\n"
    "          <p style={{color:'rgba(255,255,255,0.5)',fontSize:'1rem',marginBottom:'24px'}}>Tap anywhere to dismiss</p>\r\n"
    "          {(currentUser?.role === 'admin' || currentUser?.role === 'coordinator') && (\r\n"
    "            <button onClick={(e)=>{e.stopPropagation();handleTimerStart();setShowRotateNow(false);}} style={{\r\n"
    "              padding:'14px 32px',borderRadius:'16px',border:'none',\r\n"
    "              background:'linear-gradient(135deg,#1441a1,#60a5fa)',\r\n"
    "              color:'#fff',fontWeight:'800',fontSize:'1.1rem',cursor:'pointer',\r\n"
    "            }}>Start Next Round</button>\r\n"
    "          )}\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ UNDO SCORE FAB ═══════════════════════════════════ */}\r\n"
    "      {showUndoScore && (\r\n"
    "        <button onClick={handleUndoScore} style={{\r\n"
    "          position:'fixed',bottom:`calc(80px + env(safe-area-inset-bottom))`,right:'16px',\r\n"
    "          zIndex:8888,padding:'10px 18px',borderRadius:'24px',\r\n"
    "          border:'1px solid rgba(251,191,36,0.4)',\r\n"
    "          background:'rgba(251,191,36,0.15)',backdropFilter:'blur(12px)',\r\n"
    "          color:'#fbbf24',fontWeight:'700',fontSize:'0.85rem',cursor:'pointer',\r\n"
    "          display:'flex',alignItems:'center',gap:'6px',\r\n"
    "          boxShadow:'0 4px 20px rgba(251,191,36,0.25)',\r\n"
    "        }}>\r\n"
    "          &#8617; Undo Score\r\n"
    "        </button>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ GAME RULES QUICK-REF OVERLAY ═══════════════════ */}\r\n"
    "      {showRulesOverlay && (() => {\r\n"
    "        const roleCode = eventConfig?.servantAssignments?.[currentUser?.id];\r\n"
    "        const station = roleCode && eventConfig?.stations?.[roleCode];\r\n"
    "        return station ? (\r\n"
    "          <div style={{position:'fixed',inset:0,zIndex:8500,display:'flex',alignItems:'flex-end',background:'rgba(5,7,20,0.75)',backdropFilter:'blur(8px)'}} onClick={()=>setShowRulesOverlay(false)}>\r\n"
    "            <div onClick={e=>e.stopPropagation()} style={{width:'100%',maxHeight:'75vh',overflowY:'auto',background:'#0d1426',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'24px 24px 0 0',padding:'24px',paddingBottom:`calc(24px + env(safe-area-inset-bottom))`}}>\r\n"
    "              <div style={{width:'40px',height:'4px',borderRadius:'2px',background:'rgba(255,255,255,0.2)',margin:'0 auto 20px'}} />\r\n"
    "              <h2 style={{fontSize:'1.3rem',fontWeight:'800',color:'#fff',marginBottom:'4px'}}>{station.name}</h2>\r\n"
    "              {station.location && <p style={{fontSize:'0.8rem',color:'#60a5fa',marginBottom:'16px'}}>{station.location}</p>}\r\n"
    "              {station.howToPlay && (<div style={{marginBottom:'16px'}}><p style={{fontSize:'0.75rem',fontWeight:'700',color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.06em',marginBottom:'6px'}}>How to Play</p><p style={{fontSize:'0.9rem',color:'#fff',lineHeight:1.65,whiteSpace:'pre-wrap'}}>{station.howToPlay}</p></div>)}\r\n"
    "              {station.lesson && (<div><p style={{fontSize:'0.75rem',fontWeight:'700',color:'rgba(255,255,255,0.4)',textTransform:'uppercase',letterSpacing:'0.06em',marginBottom:'6px'}}>Lesson</p><p style={{fontSize:'0.9rem',color:'#4ade80',lineHeight:1.65}}>{station.lesson}</p></div>)}\r\n"
    "              <button onClick={()=>setShowRulesOverlay(false)} style={{marginTop:'24px',width:'100%',padding:'14px',borderRadius:'12px',border:'none',background:'linear-gradient(135deg,#1441a1,#60a5fa)',color:'#fff',fontWeight:'700',cursor:'pointer'}}>Got it</button>\r\n"
    "            </div>\r\n"
    "          </div>\r\n"
    "        ) : null;\r\n"
    "      })()}\r\n"
    "\r\n"
    "      {/* ═══ FEEDBACK MODAL ════════════════════════════════════ */}\r\n"
    "      {showFeedbackModal && (\r\n"
    "        <div style={{position:'fixed',inset:0,zIndex:8000,display:'flex',alignItems:'flex-end',background:'rgba(5,7,20,0.75)',backdropFilter:'blur(8px)'}} onClick={()=>setShowFeedbackModal(false)}>\r\n"
    "          <div onClick={e=>e.stopPropagation()} style={{width:'100%',background:'#0d1426',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'24px 24px 0 0',padding:'24px',paddingBottom:`calc(24px + env(safe-area-inset-bottom))`}}>\r\n"
    "            <div style={{width:'40px',height:'4px',borderRadius:'2px',background:'rgba(255,255,255,0.2)',margin:'0 auto 16px'}} />\r\n"
    "            <h2 style={{fontSize:'1.1rem',fontWeight:'800',color:'#fff',textAlign:'center',marginBottom:'20px'}}>Rate Today&apos;s Service</h2>\r\n"
    "            {feedbackSubmitted ? (\r\n"
    "              <div style={{textAlign:'center',padding:'24px 0',fontSize:'2rem',color:'#4ade80'}}>Thanks! &#128591;</div>\r\n"
    "            ) : (<>\r\n"
    "              <div style={{display:'flex',justifyContent:'center',gap:'12px',marginBottom:'20px'}}>\r\n"
    "                {[1,2,3,4,5].map(n=>(\r\n"
    "                  <button key={n} onClick={()=>setFeedbackRating(n)} style={{fontSize:'2rem',background:'none',border:'none',cursor:'pointer',opacity:feedbackRating>=n?1:0.25,transform:feedbackRating>=n?'scale(1.25)':'scale(1)',transition:'all 0.15s'}}>&#11088;</button>\r\n"
    "                ))}\r\n"
    "              </div>\r\n"
    "              <textarea value={feedbackText} onChange={e=>setFeedbackText(e.target.value)} placeholder='Any suggestions? (optional)' rows={3} style={{width:'100%',background:'rgba(255,255,255,0.05)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'12px',padding:'12px',color:'#fff',fontSize:'0.9rem',resize:'none',boxSizing:'border-box',marginBottom:'12px'}} />\r\n"
    "              <button onClick={handleSubmitFeedback} disabled={!feedbackRating} style={{width:'100%',padding:'14px',borderRadius:'12px',border:'none',background:feedbackRating?'linear-gradient(135deg,#1441a1,#60a5fa)':'rgba(255,255,255,0.08)',color:'#fff',fontWeight:'700',cursor:feedbackRating?'pointer':'not-allowed',opacity:feedbackRating?1:0.5}}>Submit Feedback</button>\r\n"
    "            </>)}\r\n"
    "          </div>\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ POST-SERVICE DEBRIEF MODAL ═══════════════════════ */}\r\n"
    "      {showDebriefModal && (currentUser?.role === 'admin' || currentUser?.role === 'coordinator') && (\r\n"
    "        <div style={{position:'fixed',inset:0,zIndex:8000,display:'flex',alignItems:'flex-end',background:'rgba(5,7,20,0.8)',backdropFilter:'blur(10px)'}} onClick={()=>setShowDebriefModal(false)}>\r\n"
    "          <div onClick={e=>e.stopPropagation()} style={{width:'100%',maxHeight:'90vh',overflowY:'auto',background:'#0d1426',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'24px 24px 0 0',padding:'24px',paddingBottom:`calc(24px + env(safe-area-inset-bottom))`}}>\r\n"
    "            <div style={{width:'40px',height:'4px',borderRadius:'2px',background:'rgba(255,255,255,0.2)',margin:'0 auto 20px'}} />\r\n"
    "            <h2 style={{fontSize:'1.2rem',fontWeight:'800',color:'#fff',marginBottom:'20px'}}>Post-Service Debrief</h2>\r\n"
    "            {[['kidsCount','Kids who showed up','e.g. 118','number'],['highlights','Highlights','Best moments...','textarea'],['challenges','Challenges','Any issues...','textarea'],['notes','Notes for next time','Lessons learned...','textarea']].map(([key,label,ph,type])=>(\r\n"
    "              <div key={key} style={{marginBottom:'16px'}}>\r\n"
    "                <label style={{fontSize:'0.75rem',color:'rgba(255,255,255,0.4)',display:'block',marginBottom:'6px',textTransform:'uppercase',letterSpacing:'0.06em',fontWeight:'700'}}>{label}</label>\r\n"
    "                {type==='textarea'?<textarea value={debriefData[key]||''} onChange={e=>setDebriefData(p=>({...p,[key]:e.target.value}))} placeholder={ph} rows={3} style={{width:'100%',background:'rgba(255,255,255,0.05)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'10px',padding:'10px',color:'#fff',fontSize:'0.9rem',resize:'none',boxSizing:'border-box'}}/>:<input type={type} value={debriefData[key]||''} onChange={e=>setDebriefData(p=>({...p,[key]:e.target.value}))} placeholder={ph} style={{width:'100%',background:'rgba(255,255,255,0.05)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'10px',padding:'10px',color:'#fff',fontSize:'0.9rem',boxSizing:'border-box'}}/>}\r\n"
    "              </div>\r\n"
    "            ))}\r\n"
    "            <button onClick={handleSaveDebrief} style={{width:'100%',padding:'14px',borderRadius:'12px',border:'none',background:debriefSaved?'rgba(74,222,128,0.15)':'linear-gradient(135deg,#1441a1,#60a5fa)',color:debriefSaved?'#4ade80':'#fff',fontWeight:'700',cursor:'pointer',transition:'all 0.3s'}}>{debriefSaved?'Saved! &#10003;':'Save Debrief'}</button>\r\n"
    "          </div>\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ QR CODE CHECK-IN MODAL ════════════════════════════ */}\r\n"
    "      {showQRModal && (\r\n"
    "        <div style={{position:'fixed',inset:0,zIndex:8000,display:'flex',alignItems:'center',justifyContent:'center',background:'rgba(5,7,20,0.9)',backdropFilter:'blur(14px)',padding:'24px'}} onClick={()=>setShowQRModal(false)}>\r\n"
    "          <div onClick={e=>e.stopPropagation()} style={{background:'#0d1426',border:'1px solid rgba(255,255,255,0.12)',borderRadius:'24px',padding:'32px',width:'100%',maxWidth:'320px',textAlign:'center'}}>\r\n"
    "            <h2 style={{fontSize:'1.1rem',fontWeight:'800',color:'#fff',marginBottom:'6px'}}>Self Check-in QR</h2>\r\n"
    "            <p style={{fontSize:'0.8rem',color:'rgba(255,255,255,0.4)',marginBottom:'24px'}}>{eventConfig?.eventName || 'Event'}</p>\r\n"
    "            <div style={{background:'#fff',borderRadius:'16px',padding:'16px',display:'inline-block',marginBottom:'16px'}}>\r\n"
    "              <QRCodeSVG value={window.location.origin + '/?event=' + currentEventCode + '&checkin=1'} size={190} level='M' />\r\n"
    "            </div>\r\n"
    "            <p style={{fontSize:'0.9rem',color:'rgba(255,255,255,0.4)',fontFamily:'monospace',letterSpacing:'0.15em',marginBottom:'16px'}}>{currentEventCode}</p>\r\n"
    "            <button onClick={()=>setShowQRModal(false)} style={{width:'100%',padding:'12px',borderRadius:'12px',border:'none',background:'rgba(255,255,255,0.08)',color:'#fff',fontWeight:'600',cursor:'pointer'}}>Close</button>\r\n"
    "          </div>\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ SERVANTS DIRECTORY MODAL ════════════════════════ */}\r\n"
    "      {showServantDirectoryModal && (\r\n"
    "        <div style={{position:'fixed',inset:0,zIndex:8000,display:'flex',flexDirection:'column',background:'#080b18'}}>\r\n"
    "          <div style={{padding:'16px',paddingTop:`calc(16px + env(safe-area-inset-top))`,display:'flex',alignItems:'center',gap:'12px',borderBottom:'1px solid rgba(255,255,255,0.08)',background:'rgba(13,20,38,0.95)',backdropFilter:'blur(12px)'}}>\r\n"
    "            <button onClick={()=>setShowServantDirectoryModal(false)} style={{background:'none',border:'none',color:'rgba(255,255,255,0.6)',fontSize:'1.4rem',cursor:'pointer',lineHeight:1,padding:'4px 8px'}}>&#8592;</button>\r\n"
    "            <h2 style={{fontSize:'1rem',fontWeight:'800',color:'#fff',margin:0}}>Servants Directory</h2>\r\n"
    "            <span style={{marginLeft:'auto',fontSize:'0.75rem',color:'rgba(255,255,255,0.4)',background:'rgba(255,255,255,0.06)',padding:'2px 8px',borderRadius:'8px'}}>{globalServants.length}</span>\r\n"
    "          </div>\r\n"
    "          <div style={{padding:'12px 16px',borderBottom:'1px solid rgba(255,255,255,0.05)'}}>\r\n"
    "            <input value={servantDirectorySearch} onChange={e=>setServantDirectorySearch(e.target.value)} placeholder='Search servants...' style={{width:'100%',background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'10px',padding:'10px 14px',color:'#fff',fontSize:'0.9rem',boxSizing:'border-box',outline:'none'}} />\r\n"
    "          </div>\r\n"
    "          {globalServants.length > 0 && (\r\n"
    "            <div style={{padding:'12px 16px 8px',borderBottom:'1px solid rgba(255,255,255,0.05)'}}>\r\n"
    "              <p style={{fontSize:'0.7rem',color:'#f59e0b',fontWeight:'700',textTransform:'uppercase',letterSpacing:'0.06em',marginBottom:'10px'}}>Top Servants</p>\r\n"
    "              <div style={{display:'flex',gap:'8px',overflowX:'auto',paddingBottom:'4px'}}>\r\n"
    "                {[...globalServants].sort((a,b)=>(b.servicesAttended?.length||0)-(a.servicesAttended?.length||0)).slice(0,5).map((s,i)=>(\r\n"
    "                  <div key={s.id} style={{minWidth:'76px',textAlign:'center',background:'rgba(255,255,255,0.04)',borderRadius:'12px',padding:'10px 6px',flexShrink:0}}>\r\n"
    "                    <div style={{fontSize:'1.1rem',marginBottom:'4px'}}>{['&#127945;','&#129352;','&#129353;','&#127885;','&#127885;'][i]}</div>\r\n"
    "                    <div style={{fontSize:'0.7rem',fontWeight:'700',color:'#fff',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap',maxWidth:'68px'}}>{s.name?.split(' ')[0]||'?'}</div>\r\n"
    "                    <div style={{fontSize:'0.6rem',color:'rgba(255,255,255,0.35)'}}>{s.servicesAttended?.length||0}x</div>\r\n"
    "                  </div>\r\n"
    "                ))}\r\n"
    "              </div>\r\n"
    "            </div>\r\n"
    "          )}\r\n"
    "          <div style={{flex:1,overflowY:'auto',padding:'8px 16px',paddingBottom:`calc(16px + env(safe-area-inset-bottom))`}}>\r\n"
    "            {globalServants.filter(s=>!servantDirectorySearch||s.name?.toLowerCase().includes(servantDirectorySearch.toLowerCase())).sort((a,b)=>(a.name||'').localeCompare(b.name||'')).map(s=>(\r\n"
    "              <div key={s.id} style={{background:'rgba(255,255,255,0.04)',borderRadius:'14px',padding:'14px',marginBottom:'8px',border:'1px solid rgba(255,255,255,0.06)'}}>\r\n"
    "                <div style={{display:'flex',alignItems:'center',gap:'12px',cursor:'pointer'}} onClick={()=>setExpandedServant(expandedServant===s.id?null:s.id)}>\r\n"
    "                  <div style={{width:'40px',height:'40px',borderRadius:'50%',background:'linear-gradient(135deg,#1441a1,#60a5fa)',display:'flex',alignItems:'center',justifyContent:'center',fontWeight:'800',color:'#fff',fontSize:'1rem',flexShrink:0}}>{s.name?.[0]?.toUpperCase()||'?'}</div>\r\n"
    "                  <div style={{flex:1,minWidth:0}}>\r\n"
    "                    <div style={{fontWeight:'700',color:'#fff',fontSize:'0.9rem'}}>{s.name}</div>\r\n"
    "                    <div style={{fontSize:'0.7rem',color:'rgba(255,255,255,0.35)'}}>{s.servicesAttended?.length||0} services &nbsp;&#183;&nbsp; {s.defaultRole||'volunteer'}</div>\r\n"
    "                  </div>\r\n"
    "                  <a href={getWhatsAppLink(s,'your assigned role')} target='_blank' rel='noopener noreferrer' onClick={e=>e.stopPropagation()} style={{fontSize:'1.4rem',textDecoration:'none',flexShrink:0}} title='Message on WhatsApp'>&#128172;</a>\r\n"
    "                </div>\r\n"
    "                {expandedServant===s.id && (\r\n"
    "                  <div style={{marginTop:'12px',paddingTop:'12px',borderTop:'1px solid rgba(255,255,255,0.06)'}}>\r\n"
    "                    <div style={{fontSize:'0.75rem',color:'rgba(255,255,255,0.4)',marginBottom:'4px'}}>Passcode: <span style={{color:'#fff',fontFamily:'monospace'}}>{s.passcode||'—'}</span></div>\r\n"
    "                    <div style={{fontSize:'0.75rem',color:'rgba(255,255,255,0.4)',marginBottom:'10px'}}>Last seen: <span style={{color:'#fff'}}>{s.lastSeen?new Date(s.lastSeen).toLocaleDateString():'Never'}</span></div>\r\n"
    "                    {(s.servicesAttended||[]).length > 0 && (\r\n"
    "                      <div>{(s.servicesAttended||[]).slice(-5).reverse().map((e,i)=>(\r\n"
    "                        <div key={i} style={{fontSize:'0.7rem',color:'rgba(255,255,255,0.3)',marginBottom:'2px'}}>&#183; {e.code} &mdash; {new Date(e.date).toLocaleDateString()}</div>\r\n"
    "                      ))}</div>\r\n"
    "                    )}\r\n"
    "                  </div>\r\n"
    "                )}\r\n"
    "              </div>\r\n"
    "            ))}\r\n"
    "            {globalServants.length===0 && <div style={{textAlign:'center',padding:'40px 20px',color:'rgba(255,255,255,0.3)'}}>No servants yet. They appear here when they log in.</div>}\r\n"
    "          </div>\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ GAMES LIBRARY MODAL ═══════════════════════════════ */}\r\n"
    "      {showGamesLibraryModal && (\r\n"
    "        <div style={{position:'fixed',inset:0,zIndex:8000,display:'flex',flexDirection:'column',background:'#080b18'}}>\r\n"
    "          <div style={{padding:'16px',paddingTop:`calc(16px + env(safe-area-inset-top))`,display:'flex',alignItems:'center',gap:'12px',borderBottom:'1px solid rgba(255,255,255,0.08)',background:'rgba(13,20,38,0.95)',backdropFilter:'blur(12px)'}}>\r\n"
    "            <button onClick={()=>setShowGamesLibraryModal(false)} style={{background:'none',border:'none',color:'rgba(255,255,255,0.6)',fontSize:'1.4rem',cursor:'pointer',lineHeight:1,padding:'4px 8px'}}>&#8592;</button>\r\n"
    "            <h2 style={{fontSize:'1rem',fontWeight:'800',color:'#fff',margin:0}}>Games Library</h2>\r\n"
    "            <span style={{marginLeft:'auto',fontSize:'0.75rem',color:'rgba(255,255,255,0.4)',background:'rgba(255,255,255,0.06)',padding:'2px 8px',borderRadius:'8px'}}>{gamesLibrary.length}</span>\r\n"
    "          </div>\r\n"
    "          <div style={{padding:'12px 16px',borderBottom:'1px solid rgba(255,255,255,0.05)',display:'flex',flexDirection:'column',gap:'10px'}}>\r\n"
    "            <input value={gamesLibrarySearch} onChange={e=>setGamesLibrarySearch(e.target.value)} placeholder='Search games...' style={{width:'100%',background:'rgba(255,255,255,0.06)',border:'1px solid rgba(255,255,255,0.1)',borderRadius:'10px',padding:'10px 14px',color:'#fff',fontSize:'0.9rem',boxSizing:'border-box',outline:'none'}} />\r\n"
    "            <div style={{display:'flex',gap:'6px'}}>\r\n"
    "              {['all','station','big_game','reflection'].map(f=>(\r\n"
    "                <button key={f} onClick={()=>setGamesLibraryFilter(f)} style={{padding:'6px 12px',borderRadius:'20px',border:'none',background:gamesLibraryFilter===f?'linear-gradient(135deg,#1441a1,#60a5fa)':'rgba(255,255,255,0.07)',color:'#fff',fontWeight:'600',fontSize:'0.75rem',cursor:'pointer',whiteSpace:'nowrap',flexShrink:0}}>{f==='all'?'All':f==='big_game'?'Big Game':f.charAt(0).toUpperCase()+f.slice(1)}</button>\r\n"
    "              ))}\r\n"
    "            </div>\r\n"
    "          </div>\r\n"
    "          <div style={{flex:1,overflowY:'auto',padding:'8px 16px',paddingBottom:`calc(16px + env(safe-area-inset-bottom))`}}>\r\n"
    "            {gamesLibrary.filter(g=>(gamesLibraryFilter==='all'||g.type===gamesLibraryFilter)&&(!gamesLibrarySearch||g.name?.toLowerCase().includes(gamesLibrarySearch.toLowerCase()))).map(g=>(\r\n"
    "              <div key={g.id} style={{background:'rgba(255,255,255,0.04)',borderRadius:'14px',padding:'14px',marginBottom:'8px',border:'1px solid rgba(255,255,255,0.06)'}}>\r\n"
    "                <div style={{display:'flex',alignItems:'flex-start',gap:'10px',cursor:'pointer'}} onClick={()=>setExpandedGame(expandedGame===g.id?null:g.id)}>\r\n"
    "                  <div style={{flex:1,minWidth:0}}>\r\n"
    "                    <div style={{display:'flex',alignItems:'center',gap:'8px',marginBottom:'4px',flexWrap:'wrap'}}>\r\n"
    "                      <span style={{fontWeight:'800',color:'#fff',fontSize:'0.95rem'}}>{g.name}</span>\r\n"
    "                      <span style={{fontSize:'0.65rem',padding:'2px 8px',borderRadius:'10px',background:g.type==='big_game'?'rgba(245,158,11,0.2)':g.type==='reflection'?'rgba(139,92,246,0.2)':'rgba(59,130,246,0.2)',color:g.type==='big_game'?'#f59e0b':g.type==='reflection'?'#a78bfa':'#60a5fa',fontWeight:'700'}}>{g.type==='big_game'?'Big Game':g.type?.charAt(0).toUpperCase()+(g.type?.slice(1)||'')}</span>\r\n"
    "                    </div>\r\n"
    "                    {g.location && <div style={{fontSize:'0.75rem',color:'rgba(255,255,255,0.35)',marginBottom:'4px'}}>{g.location}</div>}\r\n"
    "                    <div style={{fontSize:'0.7rem',color:'rgba(255,255,255,0.25)'}}>Used {g.timesUsed||1}x &nbsp;&#183;&nbsp; Last: {g.lastUsedEvent||'—'}</div>\r\n"
    "                  </div>\r\n"
    "                  <span style={{color:'rgba(255,255,255,0.25)',fontSize:'0.75rem',flexShrink:0,marginTop:'2px'}}>{expandedGame===g.id?'&#9650;':'&#9660;'}</span>\r\n"
    "                </div>\r\n"
    "                {expandedGame===g.id && (\r\n"
    "                  <div style={{marginTop:'12px',paddingTop:'12px',borderTop:'1px solid rgba(255,255,255,0.06)'}}>\r\n"
    "                    {g.howToPlay && <><p style={{fontSize:'0.7rem',color:'rgba(255,255,255,0.35)',fontWeight:'700',marginBottom:'4px',textTransform:'uppercase',letterSpacing:'0.06em'}}>How to Play</p><p style={{fontSize:'0.85rem',color:'#fff',lineHeight:1.65,marginBottom:'12px',whiteSpace:'pre-wrap'}}>{g.howToPlay}</p></>}\r\n"
    "                    {g.lesson && <><p style={{fontSize:'0.7rem',color:'rgba(255,255,255,0.35)',fontWeight:'700',marginBottom:'4px',textTransform:'uppercase',letterSpacing:'0.06em'}}>Lesson</p><p style={{fontSize:'0.85rem',color:'#4ade80',lineHeight:1.65}}>{g.lesson}</p></>}\r\n"
    "                  </div>\r\n"
    "                )}\r\n"
    "              </div>\r\n"
    "            ))}\r\n"
    "            {gamesLibrary.length===0&&<div style={{textAlign:'center',padding:'40px 20px',color:'rgba(255,255,255,0.3)'}}>No games saved yet. Create an event to start building the library.</div>}\r\n"
    "          </div>\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ ROTATION TIMER WIDGET (Coordinator only, floats in header) ════ */}\r\n"
    "      {rotationTimer?.startedAt && (currentUser?.role === 'admin' || currentUser?.role === 'coordinator') && (\r\n"
    "        <div style={{\r\n"
    "          position:'fixed',top:`calc(env(safe-area-inset-top) + 8px)`,right:'8px',\r\n"
    "          zIndex:700,background:'rgba(13,20,38,0.92)',backdropFilter:'blur(10px)',\r\n"
    "          border:'1px solid rgba(255,255,255,0.12)',borderRadius:'12px',\r\n"
    "          padding:'6px 12px',display:'flex',alignItems:'center',gap:'8px',\r\n"
    "        }}>\r\n"
    "          <span style={{fontSize:'0.7rem',color:rotationSecondsLeft<=60?'#f87171':'#4ade80',fontFamily:'monospace',fontWeight:'800'}}>\r\n"
    "            {rotationSecondsLeft!=null ? (Math.floor(rotationSecondsLeft/60)+':'+(rotationSecondsLeft%60<10?'0':'')+(rotationSecondsLeft%60)) : '--:--'}\r\n"
    "          </span>\r\n"
    "          {!rotationTimer.isPaused ? (\r\n"
    "            <button onClick={handleTimerPause} title='Pause' style={{background:'none',border:'none',cursor:'pointer',color:'#fbbf24',fontSize:'0.9rem',padding:'2px'}}>&#9646;&#9646;</button>\r\n"
    "          ) : (\r\n"
    "            <button onClick={handleTimerResume} title='Resume' style={{background:'none',border:'none',cursor:'pointer',color:'#4ade80',fontSize:'0.9rem',padding:'2px'}}>&#9654;</button>\r\n"
    "          )}\r\n"
    "          <button onClick={handleTimerReset} title='Reset' style={{background:'none',border:'none',cursor:'pointer',color:'rgba(255,255,255,0.4)',fontSize:'0.8rem',padding:'2px'}}>&#8635;</button>\r\n"
    "        </div>\r\n"
    "      )}\r\n"
    "\r\n"
    "      {/* ═══ OFFLINE STATUS BADGE ══════════════════════════════ */}\r\n"
    "      {!isOnline && (\r\n"
    "        <div style={{\r\n"
    "          position:'fixed',top:`calc(env(safe-area-inset-top) + 8px)`,\r\n"
    "          left:'50%',transform:'translateX(-50%)',zIndex:9000,\r\n"
    "          background:'rgba(239,68,68,0.15)',border:'1px solid rgba(239,68,68,0.4)',\r\n"
    "          color:'#f87171',borderRadius:'20px',padding:'4px 14px',\r\n"
    "          fontSize:'0.75rem',fontWeight:'700',backdropFilter:'blur(8px)',\r\n"
    "          display:'flex',alignItems:'center',gap:'6px',\r\n"
    "        }}>\r\n"
    "          <span style={{width:'6px',height:'6px',borderRadius:'50%',background:'#f87171',display:'inline-block'}} />\r\n"
    "          Offline{offlineQueueLen > 0 ? ` — ${offlineQueueLen} queued` : ''}\r\n"
    "        </div>\r\n"
    "      )}\r\n"
)

if FRAGMENT_CLOSE in src and 'showRotateNow' not in src[src.rfind('</>')-5000:]:
    src = src.replace(FRAGMENT_CLOSE, modals + FRAGMENT_CLOSE, 1)
    print("[OK] All modals inserted before closing fragment")
elif 'showRotateNow && (' in src:
    print("~ Modals already present")
else:
    print("[!!] Fragment close not found or already has modals")
    print(f"Fragment close in src: {FRAGMENT_CLOSE in src}")
    print(f"showRotateNow in last 5000: {'showRotateNow' in src[-5000:]}")

# ── 2. ADD ADMIN TOOL BUTTONS to settings tab ─────────────────────────────────
settings_anchor = "currentTab === 'settings' && currentUser && currentUser.role === 'admin' && (\r\n          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>\r\n            <h2 style={{ fontSize: '1."
if settings_anchor in src:
    settings_insert = (
        "currentTab === 'settings' && currentUser && currentUser.role === 'admin' && (\r\n"
        "          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>\r\n"
        "            {/* ── Admin Quick Tools ─────────────────────────────── */}\r\n"
        "            <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'8px',marginBottom:'4px'}}>\r\n"
        "              {[\r\n"
        "                ['&#128101; Servants','Directory',()=>setShowServantDirectoryModal(true),'#60a5fa'],\r\n"
        "                ['&#127918; Games','Library',()=>setShowGamesLibraryModal(true),'#a78bfa'],\r\n"
        "                ['&#128247; QR Check-in','Self check-in',()=>setShowQRModal(true),'#4ade80'],\r\n"
        "                ['&#128203; Debrief','Post-service',()=>setShowDebriefModal(true),'#fbbf24'],\r\n"
        "                ['&#9200; Timer','Rotation clock',()=>handleTimerStart(),'#f97316'],\r\n"
        "                [isDarkMode?'&#9728; Light':'&#9790; Dark',isDarkMode?'Switch to light':'Switch to dark',()=>setIsDarkMode(!isDarkMode),'#94a3b8'],\r\n"
        "              ].map(([title,sub,action,color])=>(\r\n"
        "                <button key={title} onClick={action} style={{padding:'14px 10px',borderRadius:'14px',border:`1px solid ${color}33`,background:`${color}0f`,color:'#fff',cursor:'pointer',textAlign:'left'}}>\r\n"
        "                  <div style={{fontWeight:'700',fontSize:'0.85rem',color}} dangerouslySetInnerHTML={{__html:title}} />\r\n"
        "                  <div style={{fontSize:'0.7rem',color:'rgba(255,255,255,0.35)',marginTop:'2px'}}>{sub}</div>\r\n"
        "                </button>\r\n"
        "              ))}\r\n"
        "            </div>\r\n"
        "            <h2 style={{ fontSize: '1."
    )
    src = src.replace(
        "currentTab === 'settings' && currentUser && currentUser.role === 'admin' && (\r\n          <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>\r\n            <h2 style={{ fontSize: '1.",
        settings_insert, 1
    )
    print("[OK] Admin tool buttons added to settings tab")
else:
    print("[!!] Settings anchor not found")

# ── 3. Rules FAB - before the bottom navigation bar ──────────────────────────
# Find bottom navigation
bottom_nav = "      {/* Bottom Navigation */}\r\n"
if bottom_nav not in src:
    bottom_nav = "      {activePingAlert &&\r\n"
    if bottom_nav not in src:
        # Try finding the nav bar by its content
        bottom_nav = "        style={{ height: 'calc(60px + env(safe-area-inset-bottom))' }}"
        if bottom_nav in src:
            # Find the start of the nav container
            nav_start = src.rfind("\r\n      <", 0, src.find(bottom_nav))
            bottom_nav_actual = src[nav_start:src.find(bottom_nav)+len(bottom_nav)]
            print(f"Nav context: {repr(bottom_nav_actual[:80])}")

rules_fab_html = (
    "      {/* ═══ GAME RULES FAB ═══════════════════════════════════ */}\r\n"
    "      {currentTab === 'service' && (() => {\r\n"
    "        const roleCode = eventConfig?.servantAssignments?.[currentUser?.id];\r\n"
    "        return roleCode && eventConfig?.stations?.[roleCode] ? (\r\n"
    "          <button onClick={() => setShowRulesOverlay(true)} title='Game Rules' style={{\r\n"
    "            position:'fixed',bottom:`calc(72px + env(safe-area-inset-bottom))`,\r\n"
    "            left:'16px',zIndex:600,width:'44px',height:'44px',borderRadius:'50%',\r\n"
    "            border:'1px solid rgba(255,255,255,0.15)',\r\n"
    "            background:'rgba(13,20,38,0.9)',backdropFilter:'blur(8px)',\r\n"
    "            color:'rgba(255,255,255,0.7)',fontSize:'1.3rem',cursor:'pointer',\r\n"
    "            display:'flex',alignItems:'center',justifyContent:'center',\r\n"
    "            boxShadow:'0 4px 16px rgba(0,0,0,0.4)',\r\n"
    "          }}>?</button>\r\n"
    "        ) : null;\r\n"
    "      })()}\r\n"
)

# Inject before closing fragment  
insert_target = "      {/* ═══ OFFLINE STATUS BADGE ══════════════════════════════ */}\r\n"
if insert_target in src:
    src = src.replace(insert_target, rules_fab_html + insert_target, 1)
    print("[OK] Rules FAB inserted")
else:
    print("[!!] Could not find offline badge to insert Rules FAB before")

# ── Save ──────────────────────────────────────────────────────────────────────
with open('src/App.jsx', 'wb') as f:
    f.write(src.encode('utf-8'))
print(f"\nDone. File: {len(src.encode('utf-8'))} bytes")
